package com.gshoaib998.progressly.ui.theme

import androidx.compose.ui.graphics.Color

// ─────────────────────────────────────────────────────────────────────────────
// THEME 1 — TERRACOTTA (default, warm earthy brown-red)
// Seed: #8F4C38
// ─────────────────────────────────────────────────────────────────────────────

val terracotta_primary_light = Color(0xFF8F4C38)
val terracotta_onPrimary_light = Color(0xFFFFFFFF)
val terracotta_primaryContainer_light = Color(0xFFFFDBD1)
val terracotta_onPrimaryContainer_light = Color(0xFF723523)
val terracotta_secondary_light = Color(0xFF77574E)
val terracotta_onSecondary_light = Color(0xFFFFFFFF)
val terracotta_secondaryContainer_light = Color(0xFFFFDBD1)
val terracotta_onSecondaryContainer_light = Color(0xFF5D4037)
val terracotta_tertiary_light = Color(0xFF6C5D2F)
val terracotta_onTertiary_light = Color(0xFFFFFFFF)
val terracotta_tertiaryContainer_light = Color(0xFFF5E1A7)
val terracotta_onTertiaryContainer_light = Color(0xFF534619)
val terracotta_error_light = Color(0xFFBA1A1A)
val terracotta_onError_light = Color(0xFFFFFFFF)
val terracotta_errorContainer_light = Color(0xFFFFDAD6)
val terracotta_onErrorContainer_light = Color(0xFF93000A)
val terracotta_background_light = Color(0xFFFFF8F6)
val terracotta_onBackground_light = Color(0xFF231917)
val terracotta_surface_light = Color(0xFFFFF8F6)
val terracotta_onSurface_light = Color(0xFF231917)
val terracotta_surfaceVariant_light = Color(0xFFF5DED8)
val terracotta_onSurfaceVariant_light = Color(0xFF53433F)
val terracotta_outline_light = Color(0xFF85736E)
val terracotta_outlineVariant_light = Color(0xFFD8C2BC)
val terracotta_inverseSurface_light = Color(0xFF392E2B)
val terracotta_inverseOnSurface_light = Color(0xFFFFEDE8)
val terracotta_inversePrimary_light = Color(0xFFFFB5A0)
val terracotta_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val terracotta_surfaceContainerLow_light = Color(0xFFFFF1ED)
val terracotta_surfaceContainer_light = Color(0xFFFCEAE5)
val terracotta_surfaceContainerHigh_light = Color(0xFFF7E4E0)
val terracotta_surfaceContainerHighest_light = Color(0xFFF1DFDA)

val terracotta_primary_dark = Color(0xFFFFB5A0)
val terracotta_onPrimary_dark = Color(0xFF561F0F)
val terracotta_primaryContainer_dark = Color(0xFF723523)
val terracotta_onPrimaryContainer_dark = Color(0xFFFFDBD1)
val terracotta_secondary_dark = Color(0xFFE7BDB2)
val terracotta_onSecondary_dark = Color(0xFF442A22)
val terracotta_secondaryContainer_dark = Color(0xFF5D4037)
val terracotta_onSecondaryContainer_dark = Color(0xFFFFDBD1)
val terracotta_tertiary_dark = Color(0xFFD8C58D)
val terracotta_onTertiary_dark = Color(0xFF3B2F05)
val terracotta_tertiaryContainer_dark = Color(0xFF534619)
val terracotta_onTertiaryContainer_dark = Color(0xFFF5E1A7)
val terracotta_error_dark = Color(0xFFFFB4AB)
val terracotta_onError_dark = Color(0xFF690005)
val terracotta_errorContainer_dark = Color(0xFF93000A)
val terracotta_onErrorContainer_dark = Color(0xFFFFDAD6)
val terracotta_background_dark = Color(0xFF1A110F)
val terracotta_onBackground_dark = Color(0xFFF1DFDA)
val terracotta_surface_dark = Color(0xFF1A110F)
val terracotta_onSurface_dark = Color(0xFFF1DFDA)
val terracotta_surfaceVariant_dark = Color(0xFF53433F)
val terracotta_onSurfaceVariant_dark = Color(0xFFD8C2BC)
val terracotta_outline_dark = Color(0xFFA08C87)
val terracotta_outlineVariant_dark = Color(0xFF53433F)
val terracotta_inverseSurface_dark = Color(0xFFF1DFDA)
val terracotta_inverseOnSurface_dark = Color(0xFF392E2B)
val terracotta_inversePrimary_dark = Color(0xFF8F4C38)
val terracotta_surfaceContainerLowest_dark = Color(0xFF140C0A)
val terracotta_surfaceContainerLow_dark = Color(0xFF231917)
val terracotta_surfaceContainer_dark = Color(0xFF271D1B)
val terracotta_surfaceContainerHigh_dark = Color(0xFF322825)
val terracotta_surfaceContainerHighest_dark = Color(0xFF3D322F)

// ─────────────────────────────────────────────────────────────────────────────
// THEME 2 — OCEAN (deep blue, calm & focused)
// Seed: #1B6091
// ─────────────────────────────────────────────────────────────────────────────

val ocean_primary_light = Color(0xFF1B6091)
val ocean_onPrimary_light = Color(0xFFFFFFFF)
val ocean_primaryContainer_light = Color(0xFFCDE5FF)
val ocean_onPrimaryContainer_light = Color(0xFF004A77)
val ocean_secondary_light = Color(0xFF4F616E)
val ocean_onSecondary_light = Color(0xFFFFFFFF)
val ocean_secondaryContainer_light = Color(0xFFD2E5F4)
val ocean_onSecondaryContainer_light = Color(0xFF384956)
val ocean_tertiary_light = Color(0xFF5C5A7E)
val ocean_onTertiary_light = Color(0xFFFFFFFF)
val ocean_tertiaryContainer_light = Color(0xFFE3DFFF)
val ocean_onTertiaryContainer_light = Color(0xFF444265)
val ocean_error_light = Color(0xFFBA1A1A)
val ocean_onError_light = Color(0xFFFFFFFF)
val ocean_errorContainer_light = Color(0xFFFFDAD6)
val ocean_onErrorContainer_light = Color(0xFF93000A)
val ocean_background_light = Color(0xFFF6FAFE)
val ocean_onBackground_light = Color(0xFF181C1F)
val ocean_surface_light = Color(0xFFF6FAFE)
val ocean_onSurface_light = Color(0xFF181C1F)
val ocean_surfaceVariant_light = Color(0xFFDDE3EA)
val ocean_onSurfaceVariant_light = Color(0xFF41484D)
val ocean_outline_light = Color(0xFF71787E)
val ocean_outlineVariant_light = Color(0xFFC1C7CE)
val ocean_inverseSurface_light = Color(0xFF2D3134)
val ocean_inverseOnSurface_light = Color(0xFFEEF1F5)
val ocean_inversePrimary_light = Color(0xFF97CBFA)
val ocean_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val ocean_surfaceContainerLow_light = Color(0xFFF0F4F8)
val ocean_surfaceContainer_light = Color(0xFFEAEEF2)
val ocean_surfaceContainerHigh_light = Color(0xFFE4E8EC)
val ocean_surfaceContainerHighest_light = Color(0xFFDEE3E7)

val ocean_primary_dark = Color(0xFF97CBFA)
val ocean_onPrimary_dark = Color(0xFF00344F)
val ocean_primaryContainer_dark = Color(0xFF004A77)
val ocean_onPrimaryContainer_dark = Color(0xFFCDE5FF)
val ocean_secondary_dark = Color(0xFFB6CAD8)
val ocean_onSecondary_dark = Color(0xFF21323E)
val ocean_secondaryContainer_dark = Color(0xFF384956)
val ocean_onSecondaryContainer_dark = Color(0xFFD2E5F4)
val ocean_tertiary_dark = Color(0xFFC5C2EB)
val ocean_onTertiary_dark = Color(0xFF2D2B4E)
val ocean_tertiaryContainer_dark = Color(0xFF444265)
val ocean_onTertiaryContainer_dark = Color(0xFFE3DFFF)
val ocean_error_dark = Color(0xFFFFB4AB)
val ocean_onError_dark = Color(0xFF690005)
val ocean_errorContainer_dark = Color(0xFF93000A)
val ocean_onErrorContainer_dark = Color(0xFFFFDAD6)
val ocean_background_dark = Color(0xFF0F1417)
val ocean_onBackground_dark = Color(0xFFDEE3E7)
val ocean_surface_dark = Color(0xFF0F1417)
val ocean_onSurface_dark = Color(0xFFDEE3E7)
val ocean_surfaceVariant_dark = Color(0xFF41484D)
val ocean_onSurfaceVariant_dark = Color(0xFFC1C7CE)
val ocean_outline_dark = Color(0xFF8B9198)
val ocean_outlineVariant_dark = Color(0xFF41484D)
val ocean_inverseSurface_dark = Color(0xFFDEE3E7)
val ocean_inverseOnSurface_dark = Color(0xFF2D3134)
val ocean_inversePrimary_dark = Color(0xFF1B6091)
val ocean_surfaceContainerLowest_dark = Color(0xFF0A0F11)
val ocean_surfaceContainerLow_dark = Color(0xFF181C1F)
val ocean_surfaceContainer_dark = Color(0xFF1C2023)
val ocean_surfaceContainerHigh_dark = Color(0xFF262B2E)
val ocean_surfaceContainerHighest_dark = Color(0xFF313639)

// ─────────────────────────────────────────────────────────────────────────────
// THEME 3 — FOREST (muted green, easy on eyes)
// Seed: #3A6B35
// ─────────────────────────────────────────────────────────────────────────────

val forest_primary_light = Color(0xFF3A6B35)
val forest_onPrimary_light = Color(0xFFFFFFFF)
val forest_primaryContainer_light = Color(0xFFBBF0B0)
val forest_onPrimaryContainer_light = Color(0xFF235220)
val forest_secondary_light = Color(0xFF52634E)
val forest_onSecondary_light = Color(0xFFFFFFFF)
val forest_secondaryContainer_light = Color(0xFFD5E8CE)
val forest_onSecondaryContainer_light = Color(0xFF3B4B37)
val forest_tertiary_light = Color(0xFF38656B)
val forest_onTertiary_light = Color(0xFFFFFFFF)
val forest_tertiaryContainer_light = Color(0xFFBCEBF1)
val forest_onTertiaryContainer_light = Color(0xFF1F4D52)
val forest_error_light = Color(0xFFBA1A1A)
val forest_onError_light = Color(0xFFFFFFFF)
val forest_errorContainer_light = Color(0xFFFFDAD6)
val forest_onErrorContainer_light = Color(0xFF93000A)
val forest_background_light = Color(0xFFF6FBF2)
val forest_onBackground_light = Color(0xFF181D17)
val forest_surface_light = Color(0xFFF6FBF2)
val forest_onSurface_light = Color(0xFF181D17)
val forest_surfaceVariant_light = Color(0xFFDEE4D9)
val forest_onSurfaceVariant_light = Color(0xFF42483F)
val forest_outline_light = Color(0xFF72796E)
val forest_outlineVariant_light = Color(0xFFC2C8BD)
val forest_inverseSurface_light = Color(0xFF2D322C)
val forest_inverseOnSurface_light = Color(0xFFEDF3E8)
val forest_inversePrimary_light = Color(0xFFA0D496)
val forest_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val forest_surfaceContainerLow_light = Color(0xFFF1F6EC)
val forest_surfaceContainer_light = Color(0xFFEBF0E6)
val forest_surfaceContainerHigh_light = Color(0xFFE5EBE1)
val forest_surfaceContainerHighest_light = Color(0xFFDFE5DB)

val forest_primary_dark = Color(0xFFA0D496)
val forest_onPrimary_dark = Color(0xFF0A3B09)
val forest_primaryContainer_dark = Color(0xFF235220)
val forest_onPrimaryContainer_dark = Color(0xFFBBF0B0)
val forest_secondary_dark = Color(0xFFB9CCB3)
val forest_onSecondary_dark = Color(0xFF243522)
val forest_secondaryContainer_dark = Color(0xFF3B4B37)
val forest_onSecondaryContainer_dark = Color(0xFFD5E8CE)
val forest_tertiary_dark = Color(0xFFA0CFD5)
val forest_onTertiary_dark = Color(0xFF00363C)
val forest_tertiaryContainer_dark = Color(0xFF1F4D52)
val forest_onTertiaryContainer_dark = Color(0xFFBCEBF1)
val forest_error_dark = Color(0xFFFFB4AB)
val forest_onError_dark = Color(0xFF690005)
val forest_errorContainer_dark = Color(0xFF93000A)
val forest_onErrorContainer_dark = Color(0xFFFFDAD6)
val forest_background_dark = Color(0xFF0F150F)
val forest_onBackground_dark = Color(0xFFDFE5DB)
val forest_surface_dark = Color(0xFF0F150F)
val forest_onSurface_dark = Color(0xFFDFE5DB)
val forest_surfaceVariant_dark = Color(0xFF42483F)
val forest_onSurfaceVariant_dark = Color(0xFFC2C8BD)
val forest_outline_dark = Color(0xFF8C9388)
val forest_outlineVariant_dark = Color(0xFF42483F)
val forest_inverseSurface_dark = Color(0xFFDFE5DB)
val forest_inverseOnSurface_dark = Color(0xFF2D322C)
val forest_inversePrimary_dark = Color(0xFF3A6B35)
val forest_surfaceContainerLowest_dark = Color(0xFF0A0F0A)
val forest_surfaceContainerLow_dark = Color(0xFF181D17)
val forest_surfaceContainer_dark = Color(0xFF1C211B)
val forest_surfaceContainerHigh_dark = Color(0xFF262C25)
val forest_surfaceContainerHighest_dark = Color(0xFF313730)

// ─────────────────────────────────────────────────────────────────────────────
// THEME 4 — VIOLET (purple, popular with devs/night owls)
// Seed: #6750A4
// ─────────────────────────────────────────────────────────────────────────────

val violet_primary_light = Color(0xFF6750A4)
val violet_onPrimary_light = Color(0xFFFFFFFF)
val violet_primaryContainer_light = Color(0xFFEADDFF)
val violet_onPrimaryContainer_light = Color(0xFF4F378B)
val violet_secondary_light = Color(0xFF625B71)
val violet_onSecondary_light = Color(0xFFFFFFFF)
val violet_secondaryContainer_light = Color(0xFFE8DEF8)
val violet_onSecondaryContainer_light = Color(0xFF4A4458)
val violet_tertiary_light = Color(0xFF7D5260)
val violet_onTertiary_light = Color(0xFFFFFFFF)
val violet_tertiaryContainer_light = Color(0xFFFFD8E4)
val violet_onTertiaryContainer_light = Color(0xFF633B48)
val violet_error_light = Color(0xFFBA1A1A)
val violet_onError_light = Color(0xFFFFFFFF)
val violet_errorContainer_light = Color(0xFFFFDAD6)
val violet_onErrorContainer_light = Color(0xFF93000A)
val violet_background_light = Color(0xFFFFFBFF)
val violet_onBackground_light = Color(0xFF1C1B1F)
val violet_surface_light = Color(0xFFFFFBFF)
val violet_onSurface_light = Color(0xFF1C1B1F)
val violet_surfaceVariant_light = Color(0xFFE7E0EC)
val violet_onSurfaceVariant_light = Color(0xFF49454F)
val violet_outline_light = Color(0xFF79747E)
val violet_outlineVariant_light = Color(0xFFCAC4D0)
val violet_inverseSurface_light = Color(0xFF313033)
val violet_inverseOnSurface_light = Color(0xFFF4EFF4)
val violet_inversePrimary_light = Color(0xFFD0BCFF)
val violet_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val violet_surfaceContainerLow_light = Color(0xFFF7F2FA)
val violet_surfaceContainer_light = Color(0xFFF3EDF7)
val violet_surfaceContainerHigh_light = Color(0xFFECE6F0)
val violet_surfaceContainerHighest_light = Color(0xFFE6E0E9)

val violet_primary_dark = Color(0xFFD0BCFF)
val violet_onPrimary_dark = Color(0xFF381E72)
val violet_primaryContainer_dark = Color(0xFF4F378B)
val violet_onPrimaryContainer_dark = Color(0xFFEADDFF)
val violet_secondary_dark = Color(0xFFCCC2DC)
val violet_onSecondary_dark = Color(0xFF332D41)
val violet_secondaryContainer_dark = Color(0xFF4A4458)
val violet_onSecondaryContainer_dark = Color(0xFFE8DEF8)
val violet_tertiary_dark = Color(0xFFEFB8C8)
val violet_onTertiary_dark = Color(0xFF492532)
val violet_tertiaryContainer_dark = Color(0xFF633B48)
val violet_onTertiaryContainer_dark = Color(0xFFFFD8E4)
val violet_error_dark = Color(0xFFFFB4AB)
val violet_onError_dark = Color(0xFF690005)
val violet_errorContainer_dark = Color(0xFF93000A)
val violet_onErrorContainer_dark = Color(0xFFFFDAD6)
val violet_background_dark = Color(0xFF141218)
val violet_onBackground_dark = Color(0xFFE6E0E9)
val violet_surface_dark = Color(0xFF141218)
val violet_onSurface_dark = Color(0xFFE6E0E9)
val violet_surfaceVariant_dark = Color(0xFF49454F)
val violet_onSurfaceVariant_dark = Color(0xFFCAC4D0)
val violet_outline_dark = Color(0xFF938F99)
val violet_outlineVariant_dark = Color(0xFF49454F)
val violet_inverseSurface_dark = Color(0xFFE6E0E9)
val violet_inverseOnSurface_dark = Color(0xFF313033)
val violet_inversePrimary_dark = Color(0xFF6750A4)
val violet_surfaceContainerLowest_dark = Color(0xFF0F0D13)
val violet_surfaceContainerLow_dark = Color(0xFF1C1B1F)
val violet_surfaceContainer_dark = Color(0xFF211F26)
val violet_surfaceContainerHigh_dark = Color(0xFF2B2930)
val violet_surfaceContainerHighest_dark = Color(0xFF36343B)

// ─────────────────────────────────────────────────────────────────────────────
// THEME 5 — SLATE (neutral blue-grey, minimal & professional)
// Seed: #455A64
// ─────────────────────────────────────────────────────────────────────────────

val slate_primary_light = Color(0xFF3D5F6F)
val slate_onPrimary_light = Color(0xFFFFFFFF)
val slate_primaryContainer_light = Color(0xFFC0E3F6)
val slate_onPrimaryContainer_light = Color(0xFF254756)
val slate_secondary_light = Color(0xFF4E6169)
val slate_onSecondary_light = Color(0xFFFFFFFF)
val slate_secondaryContainer_light = Color(0xFFD1E5EF)
val slate_onSecondaryContainer_light = Color(0xFF374951)
val slate_tertiary_light = Color(0xFF5B5C7E)
val slate_onTertiary_light = Color(0xFFFFFFFF)
val slate_tertiaryContainer_light = Color(0xFFE1E0FF)
val slate_onTertiaryContainer_light = Color(0xFF434465)
val slate_error_light = Color(0xFFBA1A1A)
val slate_onError_light = Color(0xFFFFFFFF)
val slate_errorContainer_light = Color(0xFFFFDAD6)
val slate_onErrorContainer_light = Color(0xFF93000A)
val slate_background_light = Color(0xFFF5FAFB)
val slate_onBackground_light = Color(0xFF171C1F)
val slate_surface_light = Color(0xFFF5FAFB)
val slate_onSurface_light = Color(0xFF171C1F)
val slate_surfaceVariant_light = Color(0xFFDBE4E9)
val slate_onSurfaceVariant_light = Color(0xFF3F484C)
val slate_outline_light = Color(0xFF6F787C)
val slate_outlineVariant_light = Color(0xFFBFC8CD)
val slate_inverseSurface_light = Color(0xFF2B3134)
val slate_inverseOnSurface_light = Color(0xFFECF2F5)
val slate_inversePrimary_light = Color(0xFFA4C8DA)
val slate_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val slate_surfaceContainerLow_light = Color(0xFFEFF4F6)
val slate_surfaceContainer_light = Color(0xFFE9EEF1)
val slate_surfaceContainerHigh_light = Color(0xFFE3E9EB)
val slate_surfaceContainerHighest_light = Color(0xFFDDE3E6)

val slate_primary_dark = Color(0xFFA4C8DA)
val slate_onPrimary_dark = Color(0xFF0C3141)
val slate_primaryContainer_dark = Color(0xFF254756)
val slate_onPrimaryContainer_dark = Color(0xFFC0E3F6)
val slate_secondary_dark = Color(0xFFB5C9D3)
val slate_onSecondary_dark = Color(0xFF20323A)
val slate_secondaryContainer_dark = Color(0xFF374951)
val slate_onSecondaryContainer_dark = Color(0xFFD1E5EF)
val slate_tertiary_dark = Color(0xFFC3C3EB)
val slate_onTertiary_dark = Color(0xFF2C2D4D)
val slate_tertiaryContainer_dark = Color(0xFF434465)
val slate_onTertiaryContainer_dark = Color(0xFFE1E0FF)
val slate_error_dark = Color(0xFFFFB4AB)
val slate_onError_dark = Color(0xFF690005)
val slate_errorContainer_dark = Color(0xFF93000A)
val slate_onErrorContainer_dark = Color(0xFFFFDAD6)
val slate_background_dark = Color(0xFF0E1417)
val slate_onBackground_dark = Color(0xFFDDE3E6)
val slate_surface_dark = Color(0xFF0E1417)
val slate_onSurface_dark = Color(0xFFDDE3E6)
val slate_surfaceVariant_dark = Color(0xFF3F484C)
val slate_onSurfaceVariant_dark = Color(0xFFBFC8CD)
val slate_outline_dark = Color(0xFF899297)
val slate_outlineVariant_dark = Color(0xFF3F484C)
val slate_inverseSurface_dark = Color(0xFFDDE3E6)
val slate_inverseOnSurface_dark = Color(0xFF2B3134)
val slate_inversePrimary_dark = Color(0xFF3D5F6F)
val slate_surfaceContainerLowest_dark = Color(0xFF090F11)
val slate_surfaceContainerLow_dark = Color(0xFF171C1F)
val slate_surfaceContainer_dark = Color(0xFF1B2023)
val slate_surfaceContainerHigh_dark = Color(0xFF252B2E)
val slate_surfaceContainerHighest_dark = Color(0xFF303638)
